### ISSUE TITLE
Not working on minecraft 1.17.x

### ISSUE THREAD

**Issue by Serega007RU** [BadlionNetwork/BadlionClientCPSAPI#3]
When starting the server on 1.17.1, it returns an error
```
[21:15:25 ERROR]: [BadlionClientCPSAPI] Error with config for BadlionClientCPSAPI plugin : Failed to find EntityPlayer class
java.lang.RuntimeException: Failed to find EntityPlayer class
        at net.badlion.blccpsapibukkit.listener.PlayerListener.<init>(PlayerListener.java:65) ~[badlionclientcpsapibukkit.jar:?]
        at net.badlion.blccpsapibukkit.BlcCpsApiBukkit.onEnable(BlcCpsApiBukkit.java:38) ~[badlionclientcpsapibukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-157]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-157]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-157]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
Server Core: `This server is running Paper version git-Paper-157 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f521a18)`

**Comment by Rigner** [comment]
This project has been moved to https://github.com/BadlionClient/BadlionClientModAPI and 1.18+ support has been added.
